for pol in /usr/share/fonts/Type1/n019003l.pfb
/usr/share/fonts/misc/7x13O-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Normal-Regular.woff
/usr/share/fonts/Type1/n021003l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Shapes-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_SansSerif-Bold.woff
/usr/share/fonts/TTF/DejaVuSerifCondensed.ttf
/usr/share/fonts/OTF/SyrCOMMalankara.otf
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Main-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_DoubleStruck-Bold.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_DoubleStruck-Italic.woff
/usr/share/fonts/misc/9x15.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Size1-Regular.woff
/usr/share/fonts/Type1/n021024l.pfb
/usr/share/fonts/Type1/n021004l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Size3-Regular.woff
/usr/share/fonts/misc/10x20-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Size2-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Shapes-Regular.woff
/usr/share/fonts/OTF/SyrCOMJerusalemItalic.otf
/usr/share/fonts/misc/6x13B.pcf.gz
/usr/share/fonts/OTF/SyrCOMTalada.otf
/usr/share/fonts/TTF/DejaVuSansCondensed.ttf
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_SansSerif-Italic.woff
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Size2-Regular.woff
/usr/share/fonts/misc/cu-alt12.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Size3-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_SansSerif-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Size1-Regular.woff
/usr/share/fonts/TTF/DejaVuSans-BoldOblique.ttf
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Marks-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Symbols-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Misc-Regular.woff
/usr/share/fonts/misc/10x20.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Size1-Regular.woff
/usr/share/fonts/Type1/b018035l.pfb
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Shapes-Bold.woff
/usr/share/fonts/TTF/LiberationSans-Italic.ttf
/usr/share/fonts/Type1/a010013l.pfb
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Fraktur-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Size1-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Size2-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Misc-Italic.woff
/usr/share/fonts/misc/8x13B.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Size3-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_NonUnicode-Regular.woff
/usr/share/fonts/misc/9x18B.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Size3-Regular.woff
/usr/share/fonts/misc/8x13B-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Size2-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Math-BoldItalic.woff
/usr/share/fonts/Type1/p052004l.pfb
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Monospace-Regular.woff
/usr/share/fonts/misc/7x13O.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Operators-Bold.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Main-Italic.woff
/usr/share/fonts/Type1/c059036l.pfb
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Latin-Bold.woff
/usr/share/fonts/misc/6x13O-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Monospace-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Fraktur-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Fraktur-Bold.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Normal-BoldItalic.woff
/usr/share/fonts/misc/9x18B-ISO8859-1.pcf.gz
/usr/share/fonts/TTF/DejaVuSerifCondensed-Bold.ttf
/usr/share/fonts/TTF/LiberationMono-Regular.ttf
/usr/share/fonts/Type1/s050000l.pfb
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Arrows-Regular.woff
/usr/share/fonts/OTF/SyrCOMBatnan.otf
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Size1-Regular.woff
/usr/share/fonts/misc/5x7-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_SansSerif-Regular.woff
/usr/share/fonts/misc/micro.pcf.gz
/usr/share/fonts/misc/cu-pua12.pcf.gz
/usr/share/fonts/misc/clR6x12.pcf.gz
/usr/share/fonts/misc/9x15B-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Size3-Regular.woff
/usr/share/fonts/misc/7x13B-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Size1-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Size2-Regular.woff
/usr/share/fonts/Type1/a010033l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Size3-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Size2-Regular.woff
/usr/share/fonts/TTF/DejaVuSerif-Bold.ttf
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_DoubleStruck-BoldItalic.woff
/usr/share/fonts/misc/6x9-ISO8859-1.pcf.gz
/usr/share/fonts/misc/12x24.pcf.gz
/usr/share/fonts/TTF/LiberationSans-Bold.ttf
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Normal-Bold.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_SansSerif-Bold.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Marks-Regular.woff
/usr/share/fonts/misc/cu12.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Variants-Italic.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Variants-Bold.woff
/usr/share/fonts/misc/6x13.pcf.gz
/usr/share/fonts/OTF/SyrCOMBatnanBold.otf
/usr/share/fonts/TTF/DejaVuSansMono.ttf
/usr/share/fonts/misc/5x7.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Size4-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_SansSerif-BoldItalic.woff
/usr/share/fonts/TTF/LiberationMono-BoldItalic.ttf
/usr/share/fonts/OTF/SyrCOMCtesiphon.otf
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Size5-Regular.woff
/usr/share/fonts/misc/6x13B-ISO8859-1.pcf.gz
/usr/share/fonts/misc/6x13O.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Size6-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Marks-BoldItalic.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Alphabets-Bold.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Script-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Symbols-Bold.woff
/usr/share/fonts/misc/4x6-ISO8859-1.pcf.gz
/usr/share/fonts/Type1/n019004l.pfb
/usr/share/fonts/TTF/DejaVuSerif.ttf
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Arrows-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Fraktur-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Normal-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Shapes-Regular.woff
/usr/share/fonts/Type1/c059016l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_SansSerif-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Normal-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Alphabets-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Main-Regular.woff
/usr/share/fonts/Type1/n022023l.pfb
/usr/share/fonts/misc/5x8-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Arrows-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Variants-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Operators-Regular.woff
/usr/share/fonts/misc/9x15B.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Variants-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Alphabets-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_SansSerif-Regular.woff
/usr/share/fonts/OTF/SyrCOMMardin.otf
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Alphabets-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Fraktur-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_NonUnicode-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Main-Regular.woff
/usr/share/fonts/Type1/p052024l.pfb
/usr/share/fonts/TTF/LiberationSans-Regular.ttf
/usr/share/fonts/misc/7x13-ISO8859-1.pcf.gz
/usr/share/fonts/Type1/b018015l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Script-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Alphabets-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Marks-Regular.woff
/usr/share/fonts/misc/9x18-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Alphabets-Italic.woff
/usr/share/fonts/TTF/LiberationSerif-Bold.ttf
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Operators-Regular.woff
/usr/share/fonts/misc/8x13-ISO8859-1.pcf.gz
/usr/share/fonts/Type1/n019064l.pfb
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Script-Regular.woff
/usr/share/fonts/misc/7x14B-ISO8859-1.pcf.gz
/usr/share/fonts/Type1/b018012l.pfb
/usr/share/fonts/OTF/SyrCOMMidyat.otf
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Size5-Regular.woff
/usr/share/fonts/misc/6x10-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Size4-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Size7-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_DoubleStruck-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Main-Regular.woff
/usr/share/fonts/misc/8x16.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Size6-Regular.woff
/usr/share/fonts/misc/7x14-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Symbols-Regular.woff
/usr/share/fonts/TTF/DejaVuSerifCondensed-Italic.ttf
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Main-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Script-Italic.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Symbols-Regular.woff
/usr/share/fonts/misc/9x15-ISO8859-1.pcf.gz
/usr/share/fonts/TTF/DejaVuSansCondensed-Oblique.ttf
/usr/share/fonts/TTF/DejaVuSerif-BoldItalic.ttf
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Size4-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Variants-Regular.woff
/usr/share/fonts/Type1/p052003l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Size5-Regular.woff
/usr/share/fonts/misc/18x18ko.pcf.gz
/usr/share/fonts/TTF/LiberationMono-Italic.ttf
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Monospace-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Fraktur-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Marks-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_DoubleStruck-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Math-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Latin-Regular.woff
/usr/share/fonts/TTF/DejaVuSerifCondensed-BoldItalic.ttf
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Normal-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Script-Regular.woff
/usr/share/fonts/TTF/DejaVuSansMono-Oblique.ttf
/usr/share/fonts/misc/7x14.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_NonUnicode-Regular.woff
/usr/share/fonts/Type1/n022024l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_SansSerif-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Size4-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Main-BoldItalic.woff
/usr/share/fonts/TTF/DejaVuSansCondensed-BoldOblique.ttf
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Size5-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_NonUnicode-Regular.woff
/usr/share/fonts/OTF/SyrCOMEdessa.otf
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Latin-BoldItalic.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Shapes-Regular.woff
/usr/share/fonts/misc/arabic24.pcf.gz
/usr/share/fonts/TTF/LiberationSerif-Italic.ttf
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Size4-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Symbols-Regular.woff
/usr/share/fonts/misc/deccurs.pcf.gz
/usr/share/fonts/misc/5x8.pcf.gz
/usr/share/fonts/OTF/SyrCOMUrhoyBold.otf
/usr/share/fonts/misc/8x13.pcf.gz
/usr/share/fonts/misc/7x13B.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Size5-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Marks-Italic.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Variants-BoldItalic.woff
/usr/share/fonts/OTF/SyrCOMAdiabene.otf
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Misc-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Operators-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Size4-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_DoubleStruck-Regular.woff
/usr/share/fonts/TTF/LiberationSans-BoldItalic.ttf
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_NonUnicode-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Variants-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Size6-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Main-Bold.woff
/usr/share/fonts/misc/clR6x12-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_DoubleStruck-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Operators-Regular.woff
/usr/share/fonts/misc/cursor.pcf.gz
/usr/share/fonts/OTF/SyrCOMNisibinOutline.otf
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Operators-Regular.woff
/usr/share/fonts/misc/7x14B.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Variants-Regular.woff
/usr/share/fonts/Type1/d050000l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Arrows-Regular.woff
/usr/share/fonts/TTF/LiberationSerif-BoldItalic.ttf
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Symbols-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Variants-Regular.woff
/usr/share/fonts/OTF/SyrCOMQenNeshrin.otf
/usr/share/fonts/OTF/GohaTibebZemen.otf
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Misc-Bold.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Fraktur-Regular.woff
/usr/share/fonts/Type1/p052023l.pfb
/usr/share/fonts/misc/8x13O.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Marks-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Normal-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_AMS-Regular.woff
/usr/share/fonts/Type1/n019044l.pfb
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Marks-Bold.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Marks-Regular.woff
/usr/share/fonts/TTF/LiberationSerif-Regular.ttf
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Math-Italic.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Latin-Italic.woff
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Monospace-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Arrows-Bold.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Latin-Regular.woff
/usr/share/fonts/TTF/DejaVuSans-ExtraLight.ttf
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Main-Bold.woff
/usr/share/fonts/Type1/n019063l.pfb
/usr/share/fonts/Type1/n019023l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Size5-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Arrows-Regular.woff
/usr/share/fonts/misc/18x18ja.pcf.gz
/usr/share/fonts/OTF/SyrCOMUrhoy.otf
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Size4-Regular.woff
/usr/share/fonts/TTF/GohaTibebZemen.ttf
/usr/share/fonts/Type1/c059013l.pfb
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Alphabets-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Fraktur-Regular.woff
/usr/share/fonts/Type1/n022003l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Monospace-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Caligraphic-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Misc-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Size6-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Script-Regular.woff
/usr/share/fonts/OTF/SyrCOMMardinBold.otf
/usr/share/fonts/OTF/SyrCOMNisibin.otf
/usr/share/fonts/OTF/SyrCOMKharput.otf
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Alphabets-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Misc-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Typewriter-Regular.woff
/usr/share/fonts/Type1/c059033l.pfb
/usr/share/fonts/misc/12x13ja.pcf.gz
/usr/share/fonts/Type1/z003034l.pfb
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_SansSerif-Regular.woff
/usr/share/fonts/TTF/DejaVuSans-Oblique.ttf
/usr/share/fonts/OTF/SyrCOMAntioch.otf
/usr/share/fonts/Type1/a010015l.pfb
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Shapes-BoldItalic.woff
/usr/share/fonts/Type1/n022004l.pfb
/usr/share/fonts/TTF/DejaVuSansMono-Bold.ttf
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Script-BoldItalic.woff
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Caligraphic-Bold.woff
/usr/share/fonts/misc/6x10.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Latin-Regular.woff
/usr/share/fonts/misc/decsess.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/TeX/woff/MathJax_Fraktur-Bold.woff
/usr/share/fonts/misc/9x18.pcf.gz
/usr/share/fonts/misc/4x6.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Size1-Regular.woff
/usr/share/fonts/misc/8x13O-ISO8859-1.pcf.gz
/usr/share/fonts/TTF/DejaVuSansCondensed-Bold.ttf
/usr/share/fonts/Type1/a010035l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Size2-Regular.woff
/usr/share/fonts/Type1/b018032l.pfb
/usr/share/fonts/TTF/DejaVuSerif-Italic.ttf
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Arrows-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Size3-Regular.woff
/usr/share/fonts/misc/6x12.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Neo-Euler/woff/NeoEulerMathJax_Main-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Alphabets-BoldItalic.woff
/usr/share/fonts/TTF/DejaVuSansMono-BoldOblique.ttf
/usr/share/fonts/Type1/n021023l.pfb
/usr/share/fonts/Type1/n019024l.pfb
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Script-Regular.woff
/usr/share/fonts/misc/7x13.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_SansSerif-Italic.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Shapes-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Operators-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_DoubleStruck-Regular.woff
/usr/share/fonts/OTF/SyrCOMJerusalemBold.otf
/usr/share/fonts/misc/6x12-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Shapes-Regular.woff
/usr/share/fonts/TTF/LiberationMono-Bold.ttf
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Pagella/woff/GyrePagellaMathJax_Latin-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Misc-Regular.woff
/usr/share/fonts/OTF/SyrCOMTurAbdin.otf
/usr/share/fonts/OTF/SyrCOMJerusalemOutline.otf
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Normal-Italic.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Misc-BoldItalic.woff
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Symbols-Regular.woff
/usr/share/fonts/misc/6x13-ISO8859-1.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/STIX-Web/woff/STIXMathJax_Main-Italic.woff
/usr/share/fonts/TTF/DejaVuSans.ttf
/usr/share/fonts/OTF/SyrCOMJerusalem.otf
/usr/share/fonts/Type1/n019043l.pfb
/usr/share/fonts/misc/6x9.pcf.gz
/usr/share/fonts/mathjax/HTML-CSS/Latin-Modern/woff/LatinModernMathJax_Script-Regular.woff
/usr/share/fonts/TTF/DejaVuSans-Bold.ttf
/usr/share/fonts/mathjax/HTML-CSS/Asana-Math/woff/AsanaMathJax_Main-Regular.woff
/usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Latin-Regular.woff; do dir=GyreTermesMathJax_Latin-Regular.woff;mkdir ~/ocr/training/GyreTermesMathJax_Latin-Regular.woff; for letter in {a..z}; do convert -font /usr/share/fonts/mathjax/HTML-CSS/Gyre-Termes/woff/GyreTermesMathJax_Latin-Regular.woff -pointsize 12 label:z ~/ocr/training/GyreTermesMathJax_Latin-Regular.woff/z.png; done; done
